// Generated by Rubigo. Edit the .rb source, not this file.
fn __rubigo_input(prompt: String) -> String {
    use std::io::Write;

    print!("{}", prompt);
    std::io::stdout().flush().expect("failed to flush stdout");

    let mut value = String::new();
    std::io::stdin()
        .read_line(&mut value)
        .expect("failed to read input");
    while matches!(value.as_bytes().last(), Some(&b'\n') | Some(&b'\r')) {
        value.pop();
    }
    value
}

fn main() {
    let input_1: f64 = __rubigo_input(String::from("Enter first Number")).parse::<f64>().expect("invalid numeric input");
    let input_2: f64 = __rubigo_input(String::from("Enter second Number")).parse::<f64>().expect("invalid numeric input");
    println!("{}", (input_1 + input_2));
}
