// Generated by Rubigo. Edit the .rb source, not this file.
fn main() {
    for number in 1..=20 {
        if ((number % 15) == 0) {
            println!("{}", String::from("FizzBuzz"));
        } else if ((number % 3) == 0) {
            println!("{}", String::from("Fizz"));
        } else if ((number % 5) == 0) {
            println!("{}", String::from("Buzz"));
        } else {
            println!("{}", number);
        }
    }
}
