// Generated by Rubigo. Edit the .rb source, not this file.
fn __rubigo_input(prompt: String) -> String {
    use std::io::Write;

    print!("{}", prompt);
    std::io::stdout().flush().expect("failed to flush stdout");

    let mut value = String::new();
    std::io::stdin()
        .read_line(&mut value)
        .expect("failed to read input");
    while matches!(value.as_bytes().last(), Some(&b'\n') | Some(&b'\r')) {
        value.pop();
    }
    value
}

fn __rubigo_random_int(low: i64, high: i64) -> i64 {
    assert!(low <= high, "random.int lower bound exceeds upper bound");
    let elapsed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("system time is before the Unix epoch");
    let span = (i128::from(high) - i128::from(low) + 1) as u128;
    (i128::from(low) + (elapsed.as_nanos() % span) as i128) as i64
}

fn main() {
    println!("{}", String::from("Hi! Welcome to the Number Guessing Game.\nYou have 7 chances to guess the number. Let's start!"));
    let low_bound: i64 = __rubigo_input(String::from("Enter the Lower Bound: ")).parse::<i64>().expect("invalid numeric input");
    let high_bound: i64 = __rubigo_input(String::from("Enter the Upper Bound: ")).parse::<i64>().expect("invalid numeric input");
    println!("{}", format!("\nYou have 7 chances to guess the number between {low_bound} and {high_bound}. Let's start!"));
    let number = __rubigo_random_int(low_bound, high_bound);
    let chance: i64 = 7;
    let mut guess_counter: i64 = 0;
    while guess_counter < chance {
        guess_counter += 1;
        let guess: i64 = __rubigo_input(String::from("Enter your Guess: ")).parse::<i64>().expect("invalid numeric input");
        if guess == number {
            println!("{}", format!("Correct! The number is {number}. You guessed it in {guess_counter} attempts."));
            break;
        } else if (guess_counter >= chance) && (guess != number) {
            println!("{}", format!("Sorry! The number was {number}. Better luck next time."));
        } else if guess > number {
            println!("{}", String::from("Too High! Try a lower number."));
        } else if guess < number {
            println!("{}", String::from("Too Low! Try a higher number."));
        }
    }
}
