// Generated by Rubigo. Edit the .rb source, not this file.
fn greet(name: String) -> String {
    return format!("Hello, {name}!");
}

fn main() {
    let languages: Vec<String> = vec![String::from("Rubigo"), String::from("Rust")];
    for language in languages {
        println!("{}", greet(language));
    }
    let mut total: i64 = 0;
    for number in 1..=5 {
        total = (total + number);
    }
    if (total == 15) {
        println!("{}", format!("The total is {total}."));
    } else {
        println!("{}", String::from("Something unexpected happened."));
    }
}
