// Generated by Rubigo. Edit the .rb source, not this file.
fn __rubigo_input(prompt: String) -> String {
    use std::io::Write;

    print!("{}", prompt);
    std::io::stdout().flush().expect("failed to flush stdout");

    let mut value = String::new();
    std::io::stdin()
        .read_line(&mut value)
        .expect("failed to read input");
    while matches!(value.as_bytes().last(), Some(&b'\n') | Some(&b'\r')) {
        value.pop();
    }
    value
}

fn main() {
    let name: String = __rubigo_input(String::from("What is your name? "));
    println!("{}", format!("Hello, {name}!"));
}
