from __future__ import annotations

import re

from . import ast
from .tokens import ESCAPED_LEFT_BRACE, ESCAPED_RIGHT_BRACE


TYPE_NAMES = {
    "Int": "i64",
    "Integer": "i64",
    "Float": "f64",
    "Decimal": "f64",
    "Boolean": "bool",
    "String": "String",
    "Text": "String",
    "Character": "char",
    "Nothing": "()",
    "List": "Vec",
    "Optional": "Option",
    "Result": "Result",
}

BINARY_OPERATORS = {"and": "&&", "or": "||"}
UNARY_OPERATORS = {"not": "!"}
INTERPOLATION = re.compile(r"(?<!\{)\{[A-Za-z_][A-Za-z0-9_]*(?::[^{}]+)?\}(?!\})")


class RustGenerator:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.indent = 0
        self.uses_input = False
        self.uses_random_int = False

    def generate(self, program: ast.Program) -> str:
        self._line("// Generated by Rubigo. Edit the .rb source, not this file.")
        for item in program.raw_items:
            self._line(item.code)
        if program.raw_items and program.functions:
            self._line()

        helper_position = len(self.lines)
        for index, function in enumerate(program.functions):
            self._function(function)
            if index != len(program.functions) - 1:
                self._line()

        helpers: list[str] = []
        if self.uses_input:
            helpers.extend(self._input_helper())
        if self.uses_random_int:
            if helpers:
                helpers.append("")
            helpers.extend(self._random_int_helper())
        if helpers:
            if program.functions:
                helpers.append("")
            self.lines[helper_position:helper_position] = helpers
        return "\n".join(self.lines) + "\n"

    @staticmethod
    def _input_helper() -> list[str]:
        return [
            "fn __rubigo_input(prompt: String) -> String {",
            "    use std::io::Write;",
            "",
            '    print!("{}", prompt);',
            "    std::io::stdout().flush().expect(\"failed to flush stdout\");",
            "",
            "    let mut value = String::new();",
            "    std::io::stdin()",
            "        .read_line(&mut value)",
            "        .expect(\"failed to read input\");",
            "    while matches!(value.as_bytes().last(), Some(&b'\\n') | Some(&b'\\r')) {",
            "        value.pop();",
            "    }",
            "    value",
            "}",
        ]

    @staticmethod
    def _random_int_helper() -> list[str]:
        return [
            "fn __rubigo_random_int(low: i64, high: i64) -> i64 {",
            '    assert!(low <= high, "random.int lower bound exceeds upper bound");',
            "    let elapsed = std::time::SystemTime::now()",
            "        .duration_since(std::time::UNIX_EPOCH)",
            '        .expect("system time is before the Unix epoch");',
            "    let span = (i128::from(high) - i128::from(low) + 1) as u128;",
            "    (i128::from(low) + (elapsed.as_nanos() % span) as i128) as i64",
            "}",
        ]

    def _function(self, function: ast.Function) -> None:
        visibility = "pub " if function.public else ""
        parameters = ", ".join(self._parameter(value) for value in function.parameters)
        returns = ""
        if function.return_type is not None and function.return_type.name != "Nothing":
            returns = f" -> {self._type(function.return_type)}"
        self._line(f"{visibility}fn {function.name}({parameters}){returns} {{")
        self.indent += 1
        for statement in function.body:
            self._statement(statement)
        self.indent -= 1
        self._line("}")

    def _parameter(self, parameter: ast.Parameter) -> str:
        mutable = "mut " if parameter.mutable else ""
        return f"{mutable}{parameter.name}: {self._type(parameter.type_name)}"

    def _type(self, type_name: ast.TypeName) -> str:
        name = TYPE_NAMES.get(type_name.name, type_name.name)
        if not type_name.arguments:
            return name
        arguments = ", ".join(self._type(argument) for argument in type_name.arguments)
        return f"{name}<{arguments}>"

    def _statement(self, statement: ast.Statement) -> None:
        if isinstance(statement, ast.Let):
            mutable = "mut " if statement.mutable else ""
            annotation = f": {self._type(statement.type_name)}" if statement.type_name else ""
            self._line(
                f"let {mutable}{statement.name}{annotation} = "
                f"{self._expression(statement.value, statement.type_name)};"
            )
        elif isinstance(statement, ast.Assign):
            self._line(
                f"{self._expression(statement.target)} = {self._expression(statement.value)};"
            )
        elif isinstance(statement, ast.CompoundAssign):
            self._line(
                f"{self._expression(statement.target)} {statement.operator} "
                f"{self._expression(statement.value)};"
            )
        elif isinstance(statement, ast.Print):
            if not statement.values:
                self._line("println!();")
            else:
                placeholders = " ".join("{}" for _ in statement.values)
                arguments = ", ".join(self._expression(value) for value in statement.values)
                self._line(f'println!("{placeholders}", {arguments});')
        elif isinstance(statement, ast.If):
            for index, (condition, body) in enumerate(statement.branches):
                header = f"if {self._condition(condition)} {{"
                if index == 0:
                    self._line(header)
                else:
                    self.lines[-1] += f" else {header}"
                self.indent += 1
                for child in body:
                    self._statement(child)
                self.indent -= 1
                self._line("}")
            if statement.otherwise is not None:
                self.lines[-1] += " else {"
                self.indent += 1
                for child in statement.otherwise:
                    self._statement(child)
                self.indent -= 1
                self._line("}")
        elif isinstance(statement, ast.While):
            self._line(f"while {self._condition(statement.condition)} {{")
            self.indent += 1
            for child in statement.body:
                self._statement(child)
            self.indent -= 1
            self._line("}")
        elif isinstance(statement, ast.ForEach):
            self._line(f"for {statement.name} in {self._expression(statement.iterable)} {{")
            self.indent += 1
            for child in statement.body:
                self._statement(child)
            self.indent -= 1
            self._line("}")
        elif isinstance(statement, ast.ForRange):
            operator = "..=" if statement.inclusive else ".."
            self._line(
                f"for {statement.name} in {self._expression(statement.start)}"
                f"{operator}{self._expression(statement.end)} {{"
            )
            self.indent += 1
            for child in statement.body:
                self._statement(child)
            self.indent -= 1
            self._line("}")
        elif isinstance(statement, ast.Return):
            suffix = "" if statement.value is None else f" {self._expression(statement.value)}"
            self._line(f"return{suffix};")
        elif isinstance(statement, ast.Break):
            self._line("break;")
        elif isinstance(statement, ast.Continue):
            self._line("continue;")
        elif isinstance(statement, ast.ExpressionStatement):
            self._line(f"{self._expression(statement.expression)};")
        elif isinstance(statement, ast.RawRust):
            self._line(statement.code)
        else:
            raise TypeError(f"unsupported statement: {type(statement).__name__}")

    def _condition(self, expression: ast.Expression) -> str:
        rendered = self._expression(expression)
        if isinstance(expression, (ast.Binary, ast.Unary)):
            return rendered[1:-1]
        return rendered

    def _expression(
        self, expression: ast.Expression, expected_type: ast.TypeName | None = None
    ) -> str:
        if isinstance(expression, ast.Name):
            return expression.value
        if isinstance(expression, ast.Literal):
            if expression.kind in {"integer", "decimal"}:
                return str(expression.value)
            if expression.kind == "boolean":
                return "true" if expression.value else "false"
            if expression.kind == "nothing":
                return "()"
            if expression.kind == "string":
                value = str(expression.value)
                interpolated = INTERPOLATION.search(value) is not None
                if interpolated:
                    value = value.replace(ESCAPED_LEFT_BRACE, "{{").replace(
                        ESCAPED_RIGHT_BRACE, "}}"
                    )
                else:
                    value = value.replace(ESCAPED_LEFT_BRACE, "{").replace(
                        ESCAPED_RIGHT_BRACE, "}"
                    )
                escaped = self._escape_string(value)
                if interpolated:
                    return f'format!("{escaped}")'
                return f'String::from("{escaped}")'
        if isinstance(expression, ast.ListLiteral):
            values = ", ".join(self._expression(value) for value in expression.values)
            return f"vec![{values}]"
        if isinstance(expression, ast.Unary):
            operator = UNARY_OPERATORS.get(expression.operator, expression.operator)
            return f"({operator}{self._expression(expression.operand)})"
        if isinstance(expression, ast.Binary):
            operator = BINARY_OPERATORS.get(expression.operator, expression.operator)
            return (
                f"({self._expression(expression.left)} {operator} "
                f"{self._expression(expression.right)})"
            )
        if isinstance(expression, ast.Call):
            if isinstance(expression.callee, ast.Name) and expression.callee.value == "input":
                if len(expression.arguments) > 1:
                    raise ValueError("input expects zero or one argument")
                self.uses_input = True
                prompt = (
                    "String::new()"
                    if not expression.arguments
                    else self._expression(expression.arguments[0])
                )
                input_expression = f"__rubigo_input({prompt})"
                if expected_type is not None and expected_type.name in {
                    "Int",
                    "Integer",
                    "Float",
                    "Decimal",
                }:
                    rust_type = self._type(expected_type)
                    return (
                        f'{input_expression}.parse::<{rust_type}>()'
                        '.expect("invalid numeric input")'
                    )
                return input_expression

            if (
                isinstance(expression.callee, ast.Field)
                and isinstance(expression.callee.target, ast.Name)
                and expression.callee.target.value == "random"
                and expression.callee.name == "int"
            ):
                if len(expression.arguments) != 2:
                    raise ValueError("random.int expects exactly two arguments")
                self.uses_random_int = True
                arguments = ", ".join(
                    self._expression(value) for value in expression.arguments
                )
                return f"__rubigo_random_int({arguments})"

            arguments = ", ".join(self._expression(value) for value in expression.arguments)
            if isinstance(expression.callee, ast.Name) and expression.callee.value == "length":
                if len(expression.arguments) != 1:
                    raise ValueError("length expects exactly one argument")
                return f"({self._expression(expression.arguments[0])}.len() as i64)"
            if isinstance(expression.callee, ast.Name) and expression.callee.value == "clone":
                if len(expression.arguments) != 1:
                    raise ValueError("clone expects exactly one argument")
                return f"{self._expression(expression.arguments[0])}.clone()"
            return f"{self._expression(expression.callee)}({arguments})"
        if isinstance(expression, ast.Index):
            return f"{self._expression(expression.target)}[{self._expression(expression.index)}]"
        if isinstance(expression, ast.Field):
            return f"{self._expression(expression.target)}.{expression.name}"
        raise TypeError(f"unsupported expression: {type(expression).__name__}")

    @staticmethod
    def _escape_string(value: str) -> str:
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\0", "\\0")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )

    def _line(self, value: str = "") -> None:
        self.lines.append("    " * self.indent + value)


def generate(program: ast.Program) -> str:
    return RustGenerator().generate(program)
